name: Lint code and publish Docker image

on:
  push:
    paths:
      - .github/workflows/lint_and_publish.yml
      - src/humantracker/api/*
      - src/humantracker/*.py
      - Dockerfile
      - Dockerfile.cpu-only
  workflow_dispatch:

jobs:
  lint-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
    - name: Check CPU Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile.cpu-only
    
    
      
